user = "visual"
version = "4.0.2"
last_push_time = 2024-04-03T08:32:07.938586Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <Struct: IOSurfaceSharedEventReference::MetaClass_vt membs=14 (0x80)>"
