user = "visual"
version = "4.0.2"
last_push_time = 2024-04-03T08:32:07.942177Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <Struct: AppleBCMWLANPCIeSkywalkTxCompletionQueue_vt membs=51 (0x1a8)>"
