user = "visual"
version = "4.0.2"
last_push_time = 2024-04-03T08:32:07.948255Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <Struct: AppleUSBHostControllerIsochListElement membs=1 (0x50)>"
