[metadata]
name = "AppleUSBHostControllerIsochListElement"
size = 0x50
last_change = 2024-04-03T08:32:07.948255Z

[members.0x0]
name = "vt"
offset = 0x0
type = "struct AppleUSBHostControllerIsochListElement_vt* const"
size = 0x8
